// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://flhqvkohslfxxfjzyzxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsaHF2a29oc2xmeHhmanp5enh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzY3NDQsImV4cCI6MjA2MjkxMjc0NH0.uAtsP2PNN2Y8FsDzVWoV_GcTpkQ-1vDhIFxMGOjSB3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);